### ISSUE TITLE
Mikado reproducibility issue

### ISSUE THREAD

**Issue by urmi-21** [EI-CoreBioinformatics/mikado#314]
Hello, I have been using Mikado for some time now and I discovered that I am not able to reproduce mikado results. That means that if I start with the same data and parameters (including setting the seed value) my end results (set of transcripts) are different. 
After examining closely I found that the mikado prepare step is not reproducible and hence that affects the whole pipeline (although I have not tested individual steps for reproducibility).
I have created a repository with a small dataset to demonstrate the problem. Please see https://github.com/urmi-21/mikado_test

In short: If I run the following commands without changing the data and the environment, I was expecting the same results i.e. exact same prepared.fasta and gtf, but this is not the case.

`mikado prepare --json-conf mkconf.yaml -m 100 -p 25 --seed 1234 -o m1.gtf -of m1.fasta`
`mikado prepare --json-conf mkconf.yaml -m 100 -p 25 --seed 1234 -o m2.gtf -of m2.fasta`

**My mikado version is: Mikado v2.0rc2** I have also included my conda environment file here: https://github.com/urmi-21/mikado_test/blob/master/conda_environment.yml

I hope you agree that reproducibility will be a critical issue especially when publishing results.
If you think I am doing something wrong at my end, please let me know how can I fix this issue.

**Comment by francicco** [comment]
I notice it too.
F

**Comment by lucventurini** [comment]
Dear all,

Apologies for the very late reply but I have been very busy with another project. I will be looking at your datasets now.

> In short: If I run the following commands without changing the data and the environment, I was expecting the same results i.e. exact same prepared.fasta and gtf, but this is not the case.
`mikado prepare --json-conf mkconf.yaml -m 100 -p 25 --seed 1234 -o m1.gtf -of m1.fasta
mikado prepare --json-conf mkconf.yaml -m 100 -p 25 --seed 1234 -o m2.gtf -of m2.fasta`

Yes, they should be exactly the same. You did it correctly, so if the results are not the same, this is a bug. It's surprising because we explicitly test for this feature; so many thanks for reporting!

**Comment by lucventurini** [comment]
@urmi-21 

I can reproduce on my end. I will be trying to fix it today, if not, I will have to postpone for a week as I will be away from the office from tomorrow.

**Comment by lucventurini** [comment]
Dear @urmi-21, @francicco 

134a06b fixes the issue. Briefly, `numpy.random` (which we used for randomization) is harder to set up for reproducible runs compared to `random.random`.

I have verified the correctness using your data, @urmi-21 . Your contribution is much appreciated, we would have not caught this bug otherwise!

Kind regards

**Comment by urmi-21** [comment]
@lucventurini Thanks for the update. Have you also checked serialise and pick steps for the same issue? After opening this issues i did a small test and found those steps also had this issue. May be you can confirm.
Thanks

**Comment by lucventurini** [comment]
Dear @urmi-21

I did change the culprit functions also in serialise and pick, so the problem should be solved for those steps as well.

If you were to find that that's not the case, please inform us! I'm really surprised though that serialise would not be reproducible; I am relatively confident that there is no step in it that uses randomization.

If you could share your findings, especially wet serialise, we would be very grateful.

Apologies again for having replied so late, but another project has had my full attention for the past month.

**Comment by urmi-21** [comment]
> 
> 
> Dear @urmi-21
> 
> I did change the culprit functions also in serialise and pick, so the problem should be solved for those steps as well.
> 
> If you were to find that that's not the case, please inform us! I'm really surprised though that serialise would not be reproducible; I am relatively confident that there is no step in it that uses randomization.
> 
> If you could share your findings, especially wet serialise, we would be very grateful.
> 
> Apologies again for having replied so late, but another project has had my full attention for the past month.

@lucventurini 
Sure I will let you know about the serialise and pick steps on my data. Do I need to install the newer version from source or is it updated on pip/conda?

**Comment by lucventurini** [comment]
It's updated only here on GitHub I fear, so it will have to be updated
through source download.

Many thanks!

**Comment by urmi-21** [comment]
@lucventurini Ok I have tested the latest code on GitHub and this bug does appear to be fixed :) Starting from prepare->serialise->pick is now producing consistent output.
Thanks for your efforts @lucventurini

**Comment by lucventurini** [comment]
@urmi-21 many thanks for confirming! This was an important problem, so thanks again for your detailed report. 

One bug down, others to go..

**Comment by urmi-21** [comment]
Hi @lucventurini ,

I am running into this issue again when I use a large number of GTF files. I am using 53 GTFs and result of mikado prepare is significantly different (mikado prepare runs for 6 hours). I passed the same seed value for the commands.

Output of `grep -c ">"`
```
out1/mikado_prepared.fasta: 9412205
out2/mikado_prepared.fasta: 8731375
```

I tried again using 20 GTFs and number of transcripts output by prepare step was different again.

```
546360
532390
469452
```

During mikado prepare I also encountered following exception multiple times. I am not sure if this is directly  linked with the issue or what is causing this. Even after this exception "mikado finished correctly" is displayed at the end

```
Traceback (most recent call last):
  File "/pylon5/mc5pl7p/usingh/lib/myAnacondaInstallation/envs/mikadonew/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/pylon5/mc5pl7p/usingh/lib/mikado_local/mikado/Mikado/preparation/checking.py", line 244, in run
    "SELECT features FROM dump WHERE tid = ?", (tid,)).fetchone()
  File "/pylon5/mc5pl7p/usingh/lib/myAnacondaInstallation/envs/mikadonew/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2238, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/pylon5/mc5pl7p/usingh/lib/myAnacondaInstallation/envs/mikadonew/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1006, in execute
    return self._execute_text(object_, multiparams, params)
  File "/pylon5/mc5pl7p/usingh/lib/myAnacondaInstallation/envs/mikadonew/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1181, in _execute_text
    parameters,
  File "/pylon5/mc5pl7p/usingh/lib/myAnacondaInstallation/envs/mikadonew/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1318, in _execute_context
    e, statement, parameters, cursor, context
  File "/pylon5/mc5pl7p/usingh/lib/myAnacondaInstallation/envs/mikadonew/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1512, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/pylon5/mc5pl7p/usingh/lib/myAnacondaInstallation/envs/mikadonew/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/pylon5/mc5pl7p/usingh/lib/myAnacondaInstallation/envs/mikadonew/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1278, in _execute_context
    cursor, statement, parameters, context
  File "/pylon5/mc5pl7p/usingh/lib/myAnacondaInstallation/envs/mikadonew/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: SELECT features FROM dump WHERE tid = ?]
[parameters: ('GTEX-SNMC-0826-SM-4DM66_STRG.17413.2',)]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
```

I tried my original small set of data (environment was same) (https://github.com/urmi-21/mikado_test) again and that  seems to work well. May be the problem is with larger files??

I am not able to share this data for you to test as its not published yet but I am willing to help you. So let me know if you need any more information.

BTW the reason I stumbled upon this is because after running mikado the first time, `mikado pick` step froze. The `pick.log` seemed normal without any error. So I ran mikado again and found this discrepancy in prepare step. The `mikado pick` froze this time too.

If you want I can open a separate issue for `pick` as these two issues seems to be independent.

Thank you

**Comment by urmi-21** [comment]
Some updates on my previous comment

1 The problem seems to be because of `sqlalchemy.exc.OperationalError`. If this error is not encountered results prepared.fasta files are same.

2 I am not able to figure out why `sqlalchemy.exc.OperationalError` occurs. I am not able to also perfectly reproduce the error i.e. few times mikado prepare finished with showing this error. But it does seem like if i use more GTFs its more likely to throw the error. It looks like concurrency issues with accessing the database mikado is creating.

**Comment by urmi-21** [comment]
Just want to share an important update on this issue.
Setting `-p 1` in the prepare step fixes the `sqlalchemy.exc.OperationalError` and its not too bad time wise too. So I would suggest using `-p 1` in prepare step to avoid running into errors till the issue is fixed.

**Comment by lucventurini** [comment]
Dear @urmi-21 

apologies for the late reply but I was in the process to change job (to one in which I will be dedicating more attention to Mikado).

```
1 The problem seems to be because of sqlalchemy.exc.OperationalError. If this error is not encountered results prepared.fasta files are same.

2 I am not able to figure out why sqlalchemy.exc.OperationalError occurs. I am not able to also perfectly reproduce the error i.e. few times mikado prepare finished with showing this error. But it does seem like if i use more GTFs its more likely to throw the error. It looks like concurrency issues with accessing the database mikado is creating.
```

It is difficult to diagnose from here why the errors happen sometimes but not others. Are you working on a network-attached storage at all? That could be the main suspect.

Internally `mikado prepare` sends off the data to different SQLite temporary databases to apportion it between processes. I am not the only programmer to use such a method in Python, but it has drawbacks. @ljyanesm and I are discussing whether and how to do things differently for this.

**Comment by urmi-21** [comment]
Hi @lucventurini, I was working on HPC cluster with a great file system. I don't have any reason to attribute this issue to storage/file system. I am pretty confident that this error occurs if you use large input GTFs. My data was transcript assembly on Human RNA-Seq datasets. But as I found (https://github.com/EI-CoreBioinformatics/mikado/issues/314#issuecomment-698626044) setting -p 1 solves the problem so that might be helpful for you when debugging.

**Comment by lucventurini** [comment]
Hi @urmi-21 

OK, this seals it, @ljyanesm and I will rewrite the SQLite system with something more stable.

In the meantime, you are perfectly right in your observation that using Mikado in single-thread mode will be more stable and reproducible. Doing so completely bypasses the problem, ie the SQLite data writing/reading.

Many thanks for pushing on this.

**Comment by lucventurini** [comment]
@francicco @urmi-21 

5725d2e fixes this issue for good, by using a completely different system to ferry data across processes. SQLite is no more used. I am going to apply the same strategy for `serialise` (see #327) and `pick`; once that's done, I will merge into master and close this issue.

Thank you both for pushing me to do this change and @ljyanesm for help in designing and implementing the changes.

**Comment by urmi-21** [comment]
Hi @lucventurini,
Thanks for fixing this bug. I had a chance to try out your new mikado implementation and I just wanted to share my experience. I used the latest dev version (https://github.com/EI-CoreBioinformatics/mikado/commit/0c37624ce6c2bda72d74058e8d08ce0b4ec20ab8) on my data (30 human transcriptomes assembled using stringtie) and I found that the prepare step is now extremely slow as compared to the previous implementation. Previously (this version https://github.com/EI-CoreBioinformatics/mikado/commit/134a06b32049925d6b49c480693c6cbac344b356) mikado prepare finished in 30 mins (using a single process) but now it took more than 8 hours for the same dataset !!! (i killed the job before it finished). I know you are still working on the new release and you might be already aware of this issue. In any case I just wanted to share this so you can keep this in mind while going forward.
If you already tested performance and think this might not be the case then I can try again and see if I did something wrong at my end. 
Again if you already are improving this then please ignore my comment.
Really appreciate the hard work you and your team are putting in.

**Comment by lucventurini** [comment]
Hi @urmi-21 

Many thanks for your report, no, we had not realised.

After having a look this morning, I quickly realised that the problem was my aggressive use of `zlib` to compress/decompress the data dumped to disk. Compared to just using `msgpack`, this increases the run-time of dumping/reloading by 50 times (!), and is most probably the cause of the slowdown.

This should be fixed in 875f15d. Please let us know!

**Comment by urmi-21** [comment]
Hi @lucventurini
I am still seeing the problem. I invited you to a repo that i created to test this issue. Please have a look. 
Thanks.

**Comment by lucventurini** [comment]
Hi @urmi-21 

I have downloaded the datasets now. Much appreciated, this will make the debugging and improvement much faster.

**Comment by lucventurini** [comment]
Hi @urmi-21 

I found the problems. Now your test data finishes in ~8 minutes.

Please let me know how it goes on your end.

**Comment by urmi-21** [comment]
I tried the latest commit (https://github.com/EI-CoreBioinformatics/mikado/commit/57bfb7f1f5405abff3c68705ddd18a7ef652feea) on my full dataset (30 input gtfs) and it finished in 69 minutes. As i said before, previously the time for mikado prepare on the same data was 30 mins (https://github.com/EI-CoreBioinformatics/mikado/issues/314#issuecomment-708704296).
So yea it is now able to finish mikado prepare step with multiple processes but is much slower than the sqlite version.

**Comment by lucventurini** [comment]
Dear @urmi-21 
Many thanks for confirming, though, that the version on master functions correctly.

I have worked further on the code and with 2501ba9 I should have *drastically* reduced the runtime, by identifying and correcting a couple of bottlenecks.

On your test dataset, the timing went from about 8 minutes for 57bfb7f to about 4 minutes for 2501ba9.

If this holds as I believe it should, then your full dataset should now complete again in about 30 minutes.

Apologies, in any case, for these rather quick updates. I have good hopes that 2501ba9 will be the final one required.

**Comment by urmi-21** [comment]
Ok, I just tried https://github.com/EI-CoreBioinformatics/mikado/commit/2501ba995d85e62e47165fe72592666a4c79f61a and it finished in 18 minutes!!! So thats really nice. mikado_prepared.fasta is also the same as previous. I will run the rest of the mikado pipeline and let you know if there are any other issues. Thanks for fixing these issues.

**Comment by lucventurini** [comment]
> Ok, I just tried 2501ba9 and mikado prepare finished in 18 minutes!!! So thats really nice. mikado_prepared.fasta is also the same as previous. I will run the rest of the mikado pipeline and let you know if there are any other issues. Thanks for fixing these issues.

Hi @urmi-21, that's great news! I think we finally nailed it. I will now close this issue.

Again thanks to both you and @francicco for pointing out the problem in the first place and testing, and to @ljyanesm for providing key assistance in devising ways to make Mikado faster and more robust.
